export const LANGUAGES = {
  es: {
    ADD_NEW_TASK: 'Añadir nueva tarea',
    CLEAR_ALL_TASKS: 'Borrar todas las tareas',
    EDIT_TASK: 'Editar tarea',
    DELETE_TASK: 'Eliminar tarea',
    TASK_NAME: 'Nombre de la tarea',
    ENTER_TASK_NAME :'Introduce nombre de la tarea',
    DESCRIPTION: 'Descripción',
    ENTER_TASK_DESCRIPTION :'Introduce la descripción',
    PRIORITY: 'Prioridad',
    HIGH: 'Alta',
    MEDIUM: 'Media',
    LOW: 'Baja',
    SAVE: 'Guardar',
    CANCEL: 'Cancelar',
    HEADER: 'ADMINISTRADOR TAREAS',
    FOOTER: 'Todos los derechos reservados.',
    PENDING: 'Pendiente',
    IN_PROCESS: 'En proceso',
    FINALIZED: 'Finalizado',
    RESERVED_RIGHTS:'Todos los derechos reservados.'
  },
  en: {
    ADD_NEW_TASK: 'Add New Task',
    CLEAR_ALL_TASKS: 'Clear All Tasks',
    EDIT_TASK: 'Edit Task',
    DELETE_TASK: 'Delete Task',
    TASK_NAME: 'Task Name',
    ENTER_TASK_NAME :'Enter task name',
    DESCRIPTION: 'Description',
    ENTER_TASK_DESCRIPTION :'Enter task description',
    PRIORITY: 'Priority',
    HIGH: 'High',
    MEDIUM: 'Medium',
    LOW: 'Low',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    HEADER: 'TASK MANAGER',
    FOOTER: 'All rights reserved.',
    PENDING: 'Pending',
    IN_PROCESS: 'In process',
    FINALIZED: 'Finalized',
    RESERVED_RIGHTS:'All rights reserved.'
  }
};
